### ISSUE TITLE
Support POST where GET is now required

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/cross_modality_query#14]
@SFD5311 , from your description, I think [your commit](https://github.com/hubmapconsortium/cross_modality_query/commit/dc8e122567ebca61389596e3e1fbf1e9de31f9a0) should have enabled this... but `internal.py` in the client I've tried

```python
        if input_type is None:
            # TODO: Is this really needed? Could we just send an empty POST?
            response = requests.post(request_url)
```

```python
        if input_type is None:
            # TODO: Is this really needed? Could we just send an empty POST?
            response = requests.post(request_url, {})
```

and In either case I get back 
```
'dict' object has no attribute 'dict'
```

This isn't a big deal: if practically or conceptually it doesn't seem like the right course, just drop it.

**Comment by SFD5311** [comment]
https://github.com/hubmapconsortium/cross_modality_query/commit/30ad03559ccdadfe0c143ebd77a065eedebab1c2

Looks to me like this commit enabled what you're looking for.  Either of the above methods you tried should work now.  Let me know if there's any issues.
