### ISSUE TITLE
Make sure error messages are stable

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/cross_modality_query#15]
When there are lists that go into error messages, can you sort them, so tests on the client side don't get tripped up? The strings seem to be stable right now, but I could imagine the values coming in a different order after an innocuous refactor on the api side, and I'd like to avoid that. Thanks!

**Comment by SFD5311** [comment]
This is done with this commit:
https://github.com/hubmapconsortium/cross_modality_query/commit/faa4b79301cf773c675d2ab1416d9f5b76883808
Corresponding pull request was made to client code
