### ISSUE TITLE
Investigate empty query response during CI run

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/cross_modality_query#16]
If you have server logs, could you see if there is anything weird at `Sat, 06 Feb 2021 14:04:40 GMT`? We launch a number of CI runs simultaneously, and just one of them failed, on just one line:
```
Sat, 06 Feb 2021 14:04:40 GMT   019 >>> clusters_with_gene.get_details(1)[0].keys()
Sat, 06 Feb 2021 14:04:40 GMT   UNEXPECTED EXCEPTION: IndexError('list index out of range',)
```
https://github.com/hubmapconsortium/hubmap-api-py-client/pull/45/checks?check_run_id=1845134769#step:5:41

It seems like we really did get a response back... but it was empty? If there was an error on the server, there should be an error response -- It should not return a valid, but empty, response. 

I don't know if this is enough to go on, but thought I should bring it to your attention. Thanks!

**Comment by SFD5311** [comment]
Should be fixed with commit:

https://github.com/hubmapconsortium/cross_modality_query/commit/dc50a0e8c0c83c196b08018cfba9376d0d0ad1f8
