### ISSUE TITLE
Support CORS

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/cross_modality_query#17]
Actually getting around to hitting the API from the client, and while the request goes through, the client can't read it because the server doesn't support CORS. @SFD5311 -- Let me know if more details are needed.

**Comment by SFD5311** [comment]
@mccalluc Looks like for CORS support in Django, we'll need to provide a list of allowed origins or regexes describing allowed origins.  It looks like that should be all I need for now.

**Comment by mccalluc** [comment]
At the least `hubmapconsortium.org` and all subdomains, and `localhost:5000` and `5001` ... but I think the goal of the APIs is for them to be a public resource. I'd say make it world accessible, but making it tighter temporarily is fine, too.

**Comment by SFD5311** [comment]
That makes sense.  Thanks.

**Comment by SFD5311** [comment]
Seems like this CORS support should be enabled with this commit:
https://github.com/hubmapconsortium/cross_modality_query/commit/57e672e31a182d4843853707051458fe3e49d975
But please let me know if there's continued issues
