### ISSUE TITLE
Expose cell type annotations like clusters for UI

### ISSUE THREAD

**Issue by mruffalo** [hubmapconsortium/cross_modality_query#57]

**Comment by SFD5311** [comment]
Done with commits 
https://github.com/hubmapconsortium/cross_modality_query/commit/b55747ad2469f593fe56c9b09cc1e173c5ad1dc9
and
https://github.com/hubmapconsortium/cross_modality_query/commit/484021a24dc312e7b1f5ccfe4778b40f2da0efce
