### ISSUE TITLE
Ensure consistent cell counts between API and UI

### ISSUE THREAD

**Issue by mruffalo** [hubmapconsortium/cross_modality_query#62]

**Comment by SFD5311** [comment]
Done with new index version
![Screenshot from 2022-07-21 09-36-44](https://user-images.githubusercontent.com/20894921/180227104-637cb037-1b16-408b-a99e-96d220196ddd.png)
![Screenshot from 2022-07-21 09-36-58](https://user-images.githubusercontent.com/20894921/180227106-8968e120-2c7f-4b91-aeca-56608de5504f.png)
